apiVersion: v1
kind: ConfigMap
metadata:
  name: ch-configmap
data:
  storage.xml: |
    <clickhouse>
        <storage_configuration>
            <disks>
                <hot_disk>
                    <path>/mnt/clickhouse/hot/</path>
                </hot_disk>
                <cold_disk>
                    <path>/mnt/clickhouse/cold/</path>
                </cold_disk>
            </disks>
            <policies>
                <hot_cold_policy>
                    <volumes>
                        <hot>
                            <disk>hot_disk</disk>
                        </hot>
                        <cold>
                            <disk>cold_disk</disk>
                        </cold>
                    </volumes>
                    <move_factor>0.2</move_factor>
                </hot_cold_policy>
            </policies>
        </storage_configuration>
    </clickhouse>
