apiVersion: apps/v1
kind: Deployment
metadata:
  name: clickhouse
spec:
  replicas: 1
  selector:
    matchLabels:
      app: clickhouse
  template:
    metadata:
      labels:
        app: clickhouse
    spec:
      volumes:
        - name: clickhouse-userconfigmap
          configMap:
            name: ch-configmap
        - name: clickhouse-storage
          persistentVolumeClaim:
            claimName: clickhouse
      containers:
      - name: clickhouse
        image: clickhouse/clickhouse-server
        ports:
        - containerPort: 8123
        - containerPort: 9000
        volumeMounts:
          - name: clickhouse-userconfigmap
            mountPath: /etc/clickhouse-server/config.d/storage.xml
            subPath: storage.xml
          - name: clickhouse-storage
            mountPath: /data
