apiVersion: v1
kind: PersistentVolume
metadata:
  name: clickhouse-pv
  labels:
    type: local
spec:
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: standard-rwo
  hostPath:
    path: /mnt/clickhouse
  persistentVolumeReclaimPolicy: Retain
