apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.appName }} #clickhouse
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.appName }} #clickhouse
  template:
    metadata:
      labels:
        app: {{ .Values.appName }}
    spec:
      volumes:
        - name: clickhouse-userconfigmap
          configMap:
            name: {{ .Values.configMapName }}  
        - name: clickhouse-storage
          persistentVolumeClaim:
            claimName: {{ .Values.appName }}
      containers:
        - name: clickhouse
          image:  "{{ .Values.imageName }}"           #clickhouse/clickhouse-server
          ports:
            - containerPort: 8123
              name: http
            - containerPort: 9000
              name: native
          volumeMounts:
            - name: clickhouse-userconfigmap
              mountPath: /etc/clickhouse-server/config.d/storage.xml
              subPath: storage.xml
            - name: clickhouse-storage
              mountPath: /data
