apiVersion: v1
kind: PersistentVolume
metadata:
  name: clickhouse-pv
  labels:
    type: local
spec:
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: standard-rwo
  hostPath:
    path: /mnt/clickhouse  # This should be the root path for both hot and cold disks
  persistentVolumeReclaimPolicy: Retain
