apiVersion: v1
kind: Service
metadata:
  name:   {{ .Values.appName }}    #clickhouse
spec:
  selector:
    app: {{ .Values.appName }}  #clickhouse
  ports:
  - port: 80
    targetPort: 9000
    protocol: TCP
